const list = [
  {
    id: 1,
    title: "My First Book of Pencil Control",
    author: "by Wonder House Books | 25 April 2018",
    price: 89,
    img: "https://picsum.photos/id/227/200/300",
    amount: 1,
  },
  {
    id: 2,
    title: "108 Panchatantra Stories",
    author: "by Maple Press  | 1 September 2020",
    price: 98,
    img: "https://picsum.photos/id/457/200/300",
    amount: 1,
  },
  {
    id: 3,
    title: "Amazing Questions & Answers Science",
    author: "by Om Books Editorial Team  | 25 November 2018",
    price: 143,
    img: "https://picsum.photos/id/637/200/300",
    amount: 1,
  },
  {
    id: 4,
    title: "My First Book of Pencil Control",
    author: "by Wonder House Books | 25 April 2018",
    price: 57,
    img: "https://picsum.photos/id/236/200/300",
    amount: 1,
  },
  {
    id: 5,
    title: "My First 1000 Words",
    author: "by Wonder House Books  | 1 January 2018",
    price: 149,
    img: "https://picsum.photos/id/289/200/300",
    amount: 1,
  },
  {
    id: 6,
    title: "101 Panchatantra Stories for Children",
    author: "by Om Books Editorial Team | 30 September 2020",
    price: 135,
    img: "https://picsum.photos/id/327/200/300",
    amount: 1,
  },
  {
    id: 7,
    title: "Pre-School Activities Pack ",
    author: "by Om Books Editorial Team  | 1 January 2021",
    price: 693,
    img: "https://picsum.photos/id/137/200/300",
    amount: 1,
  },
  {
    id: 8,
    title: "Early Learning Library Pack 1",
    author: "by Wonder House Books  | 6 December 2020",
    price: 289,
    img: "https://picsum.photos/id/857/200/300",
    amount: 1,
  },
  {
    id: 9,
    title: "Blossom Moral Story Book for Kids ",
    author: "by Content Team at Target Publications",
    price: 80,
    img: "https://picsum.photos/id/745/200/300",
    amount: 1,
  },
  {
    id: 10,
    title: "Brain Activity Book for Kids",
    author: "by Maple Press | 1 September 2021",
    price: 86,
    img: "https://picsum.photos/id/837/200/300",
    amount: 1,
  },
];

export default list;
